apiVersion: apps/v1
kind: Deployment

metadata:
  name: second-app-deployment

# Every deployment can be associated with only 1 container
# Pod specifications
spec:
  replicas: 2 # number of pods
  selector:
    matchLabels: # in this way we say to this deployment witch type of pod it has to control
      app: second-app
      tier: backend

  template:
    metadata:
      labels:
        app: second-app # the key name and value is up to me
        tier: backend
    spec:
      containers:
        - name: second-nodejs
          image: caldux/kub-first-app:2
